# Generated by Django 2.0.2 on 2018-04-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='acc_switch_times',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='access_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='allow_hwid',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='allow_ip',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='ban_expire',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='bonus_expire',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='first_acc_switch_time',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='last_access',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='last_server',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
