# Generated by Django 2.0.2 on 2018-04-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_account', '0002_auto_20180422_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Password'),
        ),
    ]
