# Generated by Django 2.0.2 on 2018-05-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_account', '0003_auto_20180422_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('account_name', models.CharField(max_length=45)),
                ('obj_id', models.IntegerField(db_column='obj_Id', primary_key=True, serialize=False)),
                ('char_name', models.CharField(max_length=35, unique=True)),
                ('face', models.PositiveIntegerField(blank=True, null=True)),
                ('hairstyle', models.PositiveIntegerField(blank=True, db_column='hairStyle', null=True)),
                ('haircolor', models.PositiveIntegerField(blank=True, db_column='hairColor', null=True)),
                ('sex', models.IntegerField(blank=True, null=True)),
                ('heading', models.IntegerField(blank=True, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('z', models.IntegerField(blank=True, null=True)),
                ('karma', models.IntegerField(blank=True, null=True)),
                ('pvpkills', models.IntegerField(blank=True, null=True)),
                ('pkkills', models.IntegerField(blank=True, null=True)),
                ('clanid', models.IntegerField(blank=True, null=True)),
                ('createtime', models.PositiveIntegerField()),
                ('deletetime', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=16, null=True)),
                ('rec_have', models.PositiveIntegerField()),
                ('rec_left', models.PositiveIntegerField()),
                ('rec_timeleft', models.IntegerField()),
                ('accesslevel', models.IntegerField(blank=True, null=True)),
                ('online', models.IntegerField(blank=True, null=True)),
                ('onlinetime', models.PositiveIntegerField()),
                ('lastaccess', models.PositiveIntegerField(db_column='lastAccess')),
                ('leaveclan', models.PositiveIntegerField()),
                ('deleteclan', models.PositiveIntegerField()),
                ('nochannel', models.IntegerField()),
                ('pledge_type', models.SmallIntegerField()),
                ('pledge_rank', models.PositiveIntegerField()),
                ('lvl_joined_academy', models.PositiveIntegerField()),
                ('apprentice', models.PositiveIntegerField()),
                ('key_bindings', models.CharField(blank=True, max_length=8192, null=True)),
                ('pcbangpoints', models.IntegerField(db_column='pcBangPoints')),
                ('vitality', models.PositiveSmallIntegerField()),
                ('fame', models.IntegerField()),
                ('bookmarks', models.PositiveIntegerField()),
                ('hunt_bonus', models.SmallIntegerField(blank=True, null=True)),
                ('hunt_timeleft', models.SmallIntegerField(blank=True, null=True)),
                ('bot', models.IntegerField(blank=True, null=True)),
                ('last_hwid', models.CharField(blank=True, max_length=50, null=True)),
                ('fraction', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'characters',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='acc_switch_times',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='allow_hwid',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='allow_ip',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='ban_expire',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='first_acc_switch_time',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='last_access',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='last_ip',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='last_server',
        ),
        migrations.AddField(
            model_name='accounts',
            name='activated',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accounts',
            name='allowips',
            field=models.CharField(db_column='AllowIPs', default='*', max_length=256),
        ),
        migrations.AddField(
            model_name='accounts',
            name='banexpires',
            field=models.IntegerField(db_column='banExpires', default=0),
        ),
        migrations.AddField(
            model_name='accounts',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='email',
            field=models.CharField(default='null@null', max_length=45),
        ),
        migrations.AddField(
            model_name='accounts',
            name='last_hwid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='lastactive',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accounts',
            name='lastip',
            field=models.CharField(blank=True, db_column='lastIP', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='lastserver',
            field=models.IntegerField(blank=True, db_column='lastServer', null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='lock_expire',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accounts',
            name='pay_stat',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='bonus',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='login',
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='password',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
