# Generated by Django 2.0.2 on 2018-05-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_account', '0004_auto_20180509_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='activated',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='lastserver',
            field=models.IntegerField(blank=True, db_column='lastServer', default=1, null=True),
        ),
    ]
