# Generated by Django 2.0.2 on 2018-04-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='status',
            field=models.CharField(blank=True, choices=[('cleader', 'Clan Leader'), ('pleader', 'Party Leader'), ('splayer', 'Solo Player')], max_length=255, null=True),
        ),
    ]
