# Generated by Django 2.0.2 on 2018-04-20 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_myprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='status',
            field=models.OneToOneField(blank=True, choices=[('cleader', 'Clan Leader'), ('pleader', 'Party Leader'), ('splayer', 'Solo Player')], max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to=settings.AUTH_USER_MODEL),
        ),
    ]
