# Generated by Django 2.0.2 on 2018-04-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180421_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='status',
            field=models.CharField(blank=True, choices=[('Clan Leader', 'Clan Leader'), ('Party Leader', 'Party Leader'), ('Solo Player', 'Solo Player')], max_length=255, null=True),
        ),
    ]
