# Generated by Django 2.0.2 on 2018-04-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_myprofile_account_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='account_discount',
            field=models.IntegerField(default=1, max_length=100),
        ),
    ]
