# Generated by Django 2.0.2 on 2018-04-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180423_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='account_balance',
            field=models.IntegerField(default=0),
        ),
    ]
